# Generated by Django 4.2.4 on 2023-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=100)),
                ('profile', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField(help_text='Enter your phone number (e.g., +1234567890)', max_length=15)),
                ('linkedin', models.CharField(blank=True, help_text='Enter your LinkedIn profile URL', max_length=200, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('education', models.TextField()),
                ('languages', models.TextField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('certificate', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
